language: cpp
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "ruby2.1 rake yast2-devtools yast2 yast2-testsuite" -g "yast-rake yard gettext rspec"
script:
    - rake check:syntax
    - rake check:pot
    - rake check:license
    - rake test:unit
    - sudo rake install
